name: CI
on:
  pull_request:
  push:
    branches:
      - main
env:
  BUNDLE_PATH: "./vendor/bundle"
jobs:
  generate:
    name: "Generate App From Template"
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/ci
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: ci
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby"
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - shell: bash
        name: rails new
        run: |
          TEMPLATE_HOME=`pwd`
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global init.defaultBranch main
          gem install railties --version "~> 7.0.0" --no-document
          gem install bundler --no-document
          mkdir -p ~/scratch/generated_app
          cd ~/scratch/generated_app
          rails new . -d postgresql -m $TEMPLATE_HOME/template.rb << INPUT
          ci.example.com

          INPUT
          rm -rf .git
          tar cfz ../generated_app.tgz .
      - uses: actions/upload-artifact@v3
        with:
          name: generated_app
          path: ~/scratch/generated_app.tgz
          retention-days: 1
          if-no-files-found: error
